[package]
name = "yubirs"
version = "0.2.0"
authors = ["Axel Rasmussen <axel.rasmussen1@gmail.com>"]
description = "A YubiKey OTP validation library"
homepage = "https://github.com/CmdrMoozy/yubirs"
repository = "https://github.com/CmdrMoozy/yubirs"
license = "Apache-2.0"

[dependencies]
bdrck_log = "0.3"
bdrck_params = "0.3"
chrono = "0.4"
curl = "0.4"
data-encoding = "1.2"
error-chain = "0.11"
lazy_static = "0.2"
pcsc = "0.1"
regex = "0.2"
rpassword = "1.0"
rust-crypto = "0.2"
sodiumoxide = "0.0.15"
yubico-piv-tool-sys = { path = "yubico-piv-tool-sys", version = "0.1" }
