[package]
name = "yubirs"
version = "0.2.0"
authors = ["Axel Rasmussen <axel.rasmussen1@gmail.com>"]
description = "A YubiKey OTP validation library"
homepage = "https://github.com/CmdrMoozy/yubirs"
repository = "https://github.com/CmdrMoozy/yubirs"
license = "Apache-2.0"

[dependencies]
base64 = "0.8"
bdrck = "0.4"
chrono = "0.4"
curl = "0.4"
error-chain = "0.11"
isatty = "0.1"
lazy_static = "1.0"
libc = "0.2"
log = "0.3"
pcsc = "0.1"
rand = "0.3"
regex = "0.2"
rpassword = "2.0"
rust-crypto = "0.2"
sodiumoxide = "0.0.15"
yubico-piv-tool-sys = { path = "yubico-piv-tool-sys", version = "0.1" }
